"""
Django settings for BulletinBoard project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-881&wbb1s(l^&b8ffsh+d9y79zop_^+a46rx#i$k$xm(g-#92-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1
SITE_URL = 'http://127.0.0.1:8000'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'fpages',

    'board_app',
    'accounts',
    'django_ckeditor_5',
    'allauth',  # Setting for allauth
    'allauth.account',  # Setting for allauth
    'allauth.socialaccount',  # Setting for allauth
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'BulletinBoard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BulletinBoard.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Stat
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# STATIC_ROOT = (BASE_DIR / 'static')

MEDIA_ROOT = (os.path.join(BASE_DIR, 'media'))
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Setting for celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_REDIS_SOCKET_TIMEOUT = 5

# Setting for allauth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Setting for allauth
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'

# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'test_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'test_password'

# фейковый SMTP-сервер для тестирования
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# CKEditor 5 configuration
customColorPalette = [
    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'},
]

CKEDITOR_5_CUSTOM_CSS = ''  # optional
CKEDITOR_5_FILE_STORAGE = "board_app.utils.CkeditorCustomStorage"  # optional
CKEDITOR_5_CONFIGS = {
    'default': {
        'width': '100%',
        'height': '300px',
        'resize_minWidth': '10%',
        'resize_maxWidth': '10%',
        'resize_minHeight': 300,
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link',
            'bulletedList', 'numberedList', 'blockQuote', 'imageUpload',
            'fontColor', 'fontBackgroundColor', 'mediaEmbed',
            '|',
            'undo', 'redo', '|',
            'outdent', 'indent', 'alignment:left', 'alignment:center', 'alignment:right', 'alignment:justify',
            'resize', 'move'
        ],
        'alignment': {
            'options': [
                'left',
                'right',
                'center',
                'justify'
            ]
        },
        'resize': {
            'unit': 'px',
            'minWidth': 100,
            'maxWidth': 800,
            'minHeight': 100,
            'maxHeight': 600,
            'directions': ['horizontal', 'vertical'],
            'handles': ['n', 's', 'e', 'w']
        },
        'move': {
            'x': True,
            'y': True
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:full', 'imageStyle:side',
                'imageStyle:alignLeft', 'imageStyle:alignCenter',
                'imageStyle:alignRight', 'imageStyle:alignTop',
                'imageStyle:alignBottom', 'imageStyle:alignMiddle',
                '|',
                'imageResize', 'imageResize:original',
                'imageResize:50', 'imageResize:75',
                'imageRotate', 'imageFlip',
                '|',
                'imageCrop', 'imageReset'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
                'alignTop',
                'alignBottom',
                'alignMiddle',
            ]
        },
    },
    'mediaEmbed': {
        'providers': [
            {
                'name': 'YouTube',
                'url': 'https://www.youtube.com/oembed',
                'html': '<iframe width="100%" height="100%" src="{url}" frameborder="0" allowfullscreen></iframe>'
            },
            {
                'name': 'Vimeo',
                'url': 'https://vimeo.com/api/oembed.json',
                'html': '<iframe width="100%" height="100%" src="{url}" frameborder="0" allowfullscreen></iframe>'
            }
        ]
    },

    'font': {
        'family': [
            'Arial', 'Calibri', 'Courier', 'Helvetica',
            'Times New Roman', 'Verdana'
        ],
        'size': [
            '8', '9', '10', '11', '12', '14', '16', '18', '20', '22', '24', '26', '28', '30', '32', '34', '36', '38',
            '40'
        ],
        'color': [
            '#000000', '#444444', '#666666', '#888888', '#AAAAAA', '#CCCCCC', '#EEEEEE', '#FFFFFF',
            '#FF0000', '#FF9900', '#FFFF00', '#00FF00', '#0000FF', '#9900FF', '#FF00FF'
        ],
        'backgroundColor': [
            '#FFFFFF', '#CCCCCC', '#AAAAAA', '#888888', '#666666', '#444444', '#000000',
            '#FF0000', '#FF9900', '#FFFF00', '#00FF00', '#0000FF', '#9900FF', '#FF00FF'
        ]
    },

    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': [
            'heading', '|',
            'outdent', 'indent', '|',
            'bold', 'italic', 'link',
            '|',
            'fontColor', 'fontBackgroundColor',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
            '|',
            'undo', 'redo'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:full', 'imageStyle:side',
                'imageStyle:alignLeft', 'imageStyle:alignCenter',
                'imageStyle:alignRight', 'imageStyle:alignTop',
                'imageStyle:alignBottom', 'imageStyle:alignMiddle',
                '|',
                'imageResize', 'imageResize:original',
                'imageResize:50', 'imageResize:75',
                'imageRotate', 'imageFlip',
                '|',
                'imageCrop', 'imageReset'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
                'alignTop',
                'alignBottom',
                'alignMiddle',
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        },
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
            'custom': 'true',
            'customClasses': 'true',
            'start': '1',
        },
        'styles': [
            'lower-alpha', 'lower-roman', 'upper-alpha', 'upper-roman',
            'decimal'
        ],
        'classes': {}
    }
}

# CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'jpg', 'png']
